"""Add exit_date field to User model

Revision ID: 1a80049181aa
Revises: e698d3b925db
Create Date: 2025-11-19 15:00:39.090029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a80049181aa'
down_revision = 'e698d3b925db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('exit_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('exit_date')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
