"""Add RememberedCredential model for storing saved login credentials

Revision ID: cac752f9b4ae
Revises: 1a80049181aa
Create Date: 2025-11-19 23:26:53.032773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac752f9b4ae'
down_revision = '1a80049181aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_record', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_access_record_granted_by_user', 'user', ['granted_by'], ['id'])

    with op.batch_alter_table('employee_document', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('employee_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('metadata')
        batch_op.drop_column('updated_at')

    # Create remembered_credentials table
    op.create_table('remembered_credential',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('encrypted_password', sa.String(length=255), nullable=True),
        sa.Column('device_info', sa.String(length=255), nullable=True),
        sa.Column('last_used', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remembered_credential')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('metadata', sa.TEXT(), nullable=True))

    with op.batch_alter_table('employee_settings', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('employee_document', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('access_record', schema=None) as batch_op:
        batch_op.drop_constraint('fk_access_record_granted_by_user', type_='foreignkey')

    # ### end Alembic commands ###
