"""Fix ambiguous foreign key relationships

Revision ID: e698d3b925db
Revises: 
Create Date: 2025-11-18 13:53:31.374049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e698d3b925db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('employee_id', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hire_date', sa.Date(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['manager_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('name')
        batch_op.drop_column('job_desc')
        batch_op.drop_column('summary')
        batch_op.drop_column('resume_text')
        batch_op.drop_column('score')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hire_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('manager_id')
        batch_op.drop_column('position')
        batch_op.drop_column('hire_date')
        batch_op.drop_column('status')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('resume_text', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('job_desc', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hire_date')
        batch_op.drop_column('manager_id')
        batch_op.drop_column('department')
        batch_op.drop_column('job_title')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
